---
env:
  node: true
  es6: true

parserOptions:
  ecmaVersion: 6

rules:
  # eslint:recommended
  constructor-super: 1
  no-class-assign: 1
  no-cond-assign: [1, except-parens]
  no-const-assign: 1
  no-constant-condition: 1
  no-control-regex: 1
  no-debugger: 1
  no-delete-var: 1
  no-dupe-args: 1
  no-dupe-class-members: 1
  no-dupe-keys: 1
  no-duplicate-case: 1
  no-empty-character-class: 1
  no-empty-pattern: 1
  no-ex-assign: 1
  no-extra-boolean-cast: 1
  no-extra-semi: 1
  no-fallthrough: 1
  no-func-assign: 1
  no-inner-declarations: [1, functions]
  no-invalid-regexp: 1
  no-irregular-whitespace: 1
  no-mixed-spaces-and-tabs: [1, smart-tabs]
  no-negated-in-lhs: 1
  no-new-symbol: 1
  no-obj-calls: 1
  no-octal: 1
  no-redeclare: 1
  no-regex-spaces: 1
  no-self-assign: 1
  no-sparse-arrays: 1
  no-this-before-super: 1
  no-undef: 1
  no-unexpected-multiline: 1
  no-unreachable: 1
  no-unused-vars: [1, args: none]
  use-isnan: 1
  valid-typeof: 1

  # # eslint:recommended (ignore)
  # comma-dangle: 1
  # no-case-declarations: 1
  # no-console: 1
  # no-empty: 1

  # # style
  # no-shadow: 1
  # no-unsafe-finally: 1
